# Generated by Django 4.2.3 on 2023-07-30 16:07

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('you_know', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteAccountReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.BooleanField(default=False, verbose_name='使い方がわからない')),
                ('question2', models.BooleanField(blank=True, default=False, verbose_name='同様のサービスを他で利用している')),
                ('question3', models.BooleanField(blank=True, default=False, verbose_name='データ登録等操作がし辛い')),
                ('message', models.TextField(blank=True, null=True, verbose_name='message')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created_at')),
            ],
            options={
                'db_table': 'delete_account_reason',
            },
        ),
        migrations.CreateModel(
            name='DeleteMailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=150, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
            ],
            options={
                'db_table': 'delete_mail_token',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': 'このユーザー名はすでに登録済みです。'}, help_text='150文字以内で文字や数字を使うことができます（記号は「@/./+/-/_」のみ使用可能）。', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
