# Generated by Django 4.2.3 on 2023-09-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('you_know', '0006_tag_tag_tag_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='uuid',
            new_name='id',
        ),
    ]
