# Generated by Django 4.2.3 on 2023-11-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('you_know', '0011_alter_keyword_custom_user_alter_tag_custom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='keyword',
        ),
        migrations.AddField(
            model_name='keyword',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='you_know.tag'),
        ),
    ]
