# Generated by Django 4.2.3 on 2023-12-14 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('you_know', '0014_alter_category_library_alter_keyword_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sub',
            field=models.CharField(db_index=True, editable=False, max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        #migrations.AlterField(
        #    model_name='category',
        #    name='custom_user',
        #    field=models.ForeignKey(db_column='custom_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='sub'),
        #),
        #migrations.AlterField(
        #    model_name='keyword',
        #    name='custom_user',
        #    field=models.ForeignKey(db_column='custom_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='sub'),
        #),
        #migrations.AlterField(
        #    model_name='library',
        #    name='custom_user',
        #    field=models.ForeignKey(db_column='custom_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='sub'),
        #),
        #migrations.AlterField(
        #    model_name='tag',
        #    name='custom_user',
        #    field=models.ForeignKey(db_column='custom_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='sub'),
        #),
    ]
